# --ozone-platform=wayland
--password-store=gnome
# Chạy native Wayland để giảm độ trễ và sắc nét hơn
--ozone-platform-hint=auto
--enable-features=WaylandWindowDecorations

# Tối ưu hóa render cho Intel Iris Xe
# Sử dụng OpenGL qua lớp ANGLE (ổn định hơn Vulkan trên Intel hiện tại)
--use-gl=angle
--use-angle=gl
--disable-vulkan-surface
# Tăng tốc độ vẽ (Rasterization) bằng GPU
--enable-gpu-rasterization
--enable-zero-copy

# Bật tính năng giải mã video bằng phần cứng (giảm tải CPU khi xem Youtube)
--enable-features=VaapiVideoDecodeLinuxGL
--ignore-gpu-blocklist
--enable-raw-draw
